/**
 * Strongly defined event types for VENDORA telemetry and event tracking.
 */
export const EventTypes = {
  PRODUCT_VIEW: "PRODUCT_VIEW",
  PRODUCT_CLICK: "PRODUCT_CLICK",
  PRODUCT_SEARCH: "PRODUCT_SEARCH",
  CATEGORY_VIEW: "CATEGORY_VIEW",
  WISHLIST_ADD: "WISHLIST_ADD",
  WISHLIST_REMOVE: "WISHLIST_REMOVE",
  CART_ADD: "CART_ADD",
  CART_REMOVE: "CART_REMOVE",
  CHECKOUT_START: "CHECKOUT_START",
  PURCHASE: "PURCHASE",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  REFUND_REQUESTED: "REFUND_REQUESTED",
  REVIEW_SUBMITTED: "REVIEW_SUBMITTED",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  DEVICE_SEEN: "DEVICE_SEEN",
  SECURITY_EVENT: "SECURITY_EVENT",

  // Recommendation tracking
  RECOMMENDATION_IMPRESSION: "RECOMMENDATION_IMPRESSION",
  RECOMMENDATION_CLICK: "RECOMMENDATION_CLICK",
  RECOMMENDATION_PURCHASE: "RECOMMENDATION_PURCHASE",

  // AI assistant tracking
  AI_ASSISTANT_OPEN: "AI_ASSISTANT_OPEN",
  AI_QUERY: "AI_QUERY",
  AI_SEARCH: "AI_SEARCH",
  AI_RECOMMENDATION: "AI_RECOMMENDATION",
  AI_PRODUCT_CLICK: "AI_PRODUCT_CLICK",
  AI_COMPARISON: "AI_COMPARISON",
  AI_ORDER_QUERY: "AI_ORDER_QUERY",
  AI_ERROR: "AI_ERROR"
};
